### ISSUE TITLE
Call the Class HomeViewController

### ISSUE THREAD

**Issue by IvanMaoCode** [itsjohnye/Lead-iOS-Demo#3]
Hi, I just want to ask what parameters should i replace for the NSCoder, code as below:
let homeVc = HomeViewController(coder: NSCoder)
![截屏2019-11-1919 18 01](https://user-images.githubusercontent.com/54170361/69142259-64121180-0b01-11ea-9c4e-1aebc975f2cd.png)

**Comment by itsjohnye** [comment]
@IvanMaoCode Please show more contents

**Comment by IvanMaoCode** [comment]
@itsjohnye  The Class you create as picture
<img width="1058" alt="HomeViewController-Class" src="https://user-images.githubusercontent.com/54170361/69166179-cb45bb00-0b2d-11ea-8331-27171de925d0.png">
and how I declare the Class HomeViewController, because i want to call its one func 我想调用HomeViewController 里面的一个方法，代码如何声明这个类？

**Comment by itsjohnye** [comment]
@IvanMaoCode 
Highly not recommend you to create an instance for an initialized UIViewController, because it may cause an infinite loop.

Using _NotificationCenter_ or _Delegate_ for communications among View Controllers.

Alternatively, do something like instantiate a view controller using its Storyboard name：
```
    let storyboard = UIStoryboard(name: "Main", bundle: nil)

    let homeVC = storyboard.instantiateViewController(withIdentifier: "HomeViewController") as! HomeViewController

    homeVC.yourFunction()
```
